#!/bin/bash
cd ~/modupdater-java/ModUpdater

if [ -f .apikey ]; then API_KEY=$(cat .apikey); fi # Just set the API_KEY env to the contents of the .apikey file (for running the test command thingy)

if [[ "x$1" == "xall" ]]; then
	mvn clean compile assembly:single package site site-deploy || exit 1
else
	mvn compile assembly:single package || exit 1
fi

VERSION=$(cat pom.xml | grep "<version>" | sed -e 's/.*<version>//g;s/<\/v.*//g' | sed -n '1p')
cp target/modupdater-$VERSION-jar-with-dependencies.jar downloads/
./execute

